services:
  - type: web
    name: roxin-site
    env: python
    plan: free
    buildCommand: ./build.sh
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 2 --timeout 120
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: roxin-db
          property: connectionString
      - key: PYTHON_VERSION
        value: 3.11.5
    healthCheckPath: /
  
databases:
  - name: roxin-db
    databaseName: roxin
    user: roxin_user
    plan: free 