services:
  - type: web
    name: roxin-site
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 1 --timeout 120
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        value: postgresql://postgres.lgaybwinuhssjoyyyxkn:UNFtXoJfQsL5E1py@aws-0-eu-central-1.pooler.supabase.com:6543/postgres
    healthCheckPath: / 